pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["../author_info/about.html","About Author","About the Author Currently there are many of the open source projects I participate and develop listed on my website. On my sourceforge user page ...",""],
["../author_info/contact.html","Contact","Contact the Author Sam Gleske http://www.pages.drexel.edu/~sag47/ ",""],
["../author_info/contributors.html","Contributors","Contributors The following are contributors who helped this calculator along the way: name - year contributed Kyle Winters - 2005 Chad Carreras - ...",""],
["../author_info/resume.html","Resume","Resume Request If you would like to see my resume then you must request it because I don&#39;t post it online. You can simply email me (my email is in...",""],
["../author_info/tech.html","Technologies used","Technologies This section discusses the technologies that were used to create the calculator and this help system. First of all, the web languages...",""],
["../button_help/about_btns.html","Button Overview","About Buttons This section is to teach you how to use the different buttons of the Scientific Calculator. You will learn the names of the function...",""],
["../button_help/basic_eqtns.html","Basic Equations","Basic Equation Buttons Above are the basic calculator buttons found on every calculator. Rules: There has to be a symbol in between any two algebr...",""],
["../button_help/del_btn.html","Deletion Buttons","Deletion Buttons There are several ways to remove variables or entire equations from the display or memory of the Scientific Calculator. The next ...",""],
["../button_help/mem_fxn.html","Memory Buttons","Memory Buttons In this help topic you will learn how to use the memory functions of the Scientific Calculator. At the top you should recognize the...",""],
["../button_help/misc.html","Miscellaneous","Miscellaneous The rest of the button functions of the Scientific Calculator fall into this category.After you read this you will be scott free and...",""],
["../button_help/pow.html","Power Functions","Power Functions Now we discuss power functions. Look at the picture below for a list of the power function buttons: The first power function we sh...",""],
["../button_help/trig.html","Trigonometric Functions","Trigonometric Functions At the top you can select a mode for the trig functions to be calculated in, Degrees or Radians. Depending on what you nee...",""],
["../calc_info.html","Calc Info","About What is the Scientific Calculator v1.3.3? It is an advanced calculator that uses JavaScript (not Java) to compute advanced math functions.Ty...",""],
["../compatible_browsers.html","Compatible Browsers","Compatible Browsers Scientific Calculator v1.3.x fully supports the following web browsers on all platforms: Firefox Internet Explorer 6.0+ Konque...",""],
["../license/disclaimer.html","Disclaimer","Warning! I do my best to make sure all the calculations and conversions are accurate and correct. But there is always the possibility that they ar...",""],
["../license/license.html","License","License Copyright &#169; 2005 Sam Gleske Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated d...",""],
["../menu_help/about_menu.html","Menu Overview","About Menu What is the menu? What is a submenu? A submenu is a branch within the main headers of the menu. Click on the main header File. You will...",""],
["../menu_help/conv_menu.html","Conv Menu","Conv Menu Header What is the Conv Menu? What does Conv mean? Conv is abbreviated for Convert. It&#39;s purpose is to convert between common units. Fun...",""],
["../menu_help/edit_menu.html","Edit Menu","Edit Menu Header What is the Edit Menu? Functions of the Edit Menu: Edit Copy Copies the diplayed equation Edit Paste Pastes contents of clipboard...",""],
["../menu_help/file_menu.html","File Menu","File Menu Header What is the File Menu? Functions of the File Menu: Under File Reload: This submenu resets all settings of the calculator Under Fi...",""],
["../menu_help/help_menu.html","Help Menu","Help Menu Header What is the Help Menu? Functions of the Help Menu: Help Help Displays the help database (this entire help guide). Help About Disp...",""],
["../shortcuts.html","Keyboard Shortcuts","Keyboard Shortcuts All the Basic Equation Keys work (0-9+-*/^% .) MC press C key MR press R key MS press S key M+ press M key pi press P key () pr...",""],
["../welcome.html","Welcome","Welcome Welcome to the Scientific Calculator v1.3.3 Help Database. Here you will find extensive knowledge and expertise with the function of this ...",""]];
